# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edgeOnLoop <- function(fromNode, toNode, parSet) {
    .Call(`_dagbagMv2_edgeOnLoop`, fromNode, toNode, parSet)
}

hc1 <- function(Y, nodeType, whiteList, blackList, tol = 1e-6, maxStep = 500L, seed = 1L, flip = TRUE, verbose = FALSE, debug = FALSE, addDeleteOnly = FALSE) {
    .Call(`_dagbagMv2_hc1`, Y, nodeType, whiteList, blackList, tol, maxStep, seed, flip, verbose, debug, addDeleteOnly)
}

hc_ <- function(Y, nodeType, whiteList, blackList, tol = 1e-6, maxStep = 500L, restart = 1L, seed = 1L, verbose = FALSE, debug = FALSE, addDeleteOnly = FALSE) {
    .Call(`_dagbagMv2_hc_`, Y, nodeType, whiteList, blackList, tol, maxStep, restart, seed, verbose, debug, addDeleteOnly)
}

score_shd_freq_cpp <- function(freq, alpha, threshold, whitelist, blacklist, verbose = FALSE) {
    .Call(`_dagbagMv2_score_shd_freq_cpp`, freq, alpha, threshold, whitelist, blacklist, verbose)
}

score_shd_cpp <- function(bootAdj, alpha, threshold, whitelist, blacklist, verbose = FALSE) {
    .Call(`_dagbagMv2_score_shd_cpp`, bootAdj, alpha, threshold, whitelist, blacklist, verbose)
}

