// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hc1
Rcpp::List hc1(const Rcpp::NumericMatrix& Y, const Rcpp::CharacterVector& nodeType, const Rcpp::LogicalMatrix& whiteList, const Rcpp::LogicalMatrix& blackList, double tol, unsigned int maxStep, unsigned int seed, bool flip, bool verbose);
RcppExport SEXP _dagbagM_hc1(SEXP YSEXP, SEXP nodeTypeSEXP, SEXP whiteListSEXP, SEXP blackListSEXP, SEXP tolSEXP, SEXP maxStepSEXP, SEXP seedSEXP, SEXP flipSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type nodeType(nodeTypeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalMatrix& >::type whiteList(whiteListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalMatrix& >::type blackList(blackListSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type maxStep(maxStepSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type flip(flipSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(hc1(Y, nodeType, whiteList, blackList, tol, maxStep, seed, flip, verbose));
    return rcpp_result_gen;
END_RCPP
}
// hc_
Rcpp::List hc_(const Rcpp::NumericMatrix& Y, const Rcpp::CharacterVector& nodeType, const Rcpp::LogicalMatrix& whiteList, const Rcpp::LogicalMatrix& blackList, double tol, unsigned int maxStep, unsigned int restart, unsigned int seed, bool verbose);
RcppExport SEXP _dagbagM_hc_(SEXP YSEXP, SEXP nodeTypeSEXP, SEXP whiteListSEXP, SEXP blackListSEXP, SEXP tolSEXP, SEXP maxStepSEXP, SEXP restartSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type nodeType(nodeTypeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalMatrix& >::type whiteList(whiteListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalMatrix& >::type blackList(blackListSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type maxStep(maxStepSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type restart(restartSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(hc_(Y, nodeType, whiteList, blackList, tol, maxStep, restart, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}



static const R_CallMethodDef CallEntries[] = {
    {"_dagbagM_hc1", (DL_FUNC) &_dagbagM_hc1, 9},
    {"_dagbagM_hc_", (DL_FUNC) &_dagbagM_hc_, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_dagbagM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
