# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hc <- function(Y, nodeType, whiteList, blackList, tol = 1e-6, maxStep = 500L, verbose = FALSE) {
    .Call(`_dagbagM_hc`, Y, nodeType, whiteList, blackList, tol, maxStep, verbose)
}

rcpp_hello_world <- function() {
    .Call(`_dagbagM_rcpp_hello_world`)
}

