# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hc1 <- function(Y, nodeType, whiteList, blackList, tol = 1e-6, maxStep = 500L, seed = 1L, flip = TRUE, verbose = FALSE) {
    .Call(`_dagbagM_hc1`, Y, nodeType, whiteList, blackList, tol, maxStep, seed, flip, verbose)
}

hc_ <- function(Y, nodeType, whiteList, blackList, tol = 1e-6, maxStep = 500L, restart = 10L, seed = 1L, verbose = FALSE) {
    .Call(`_dagbagM_hc_`, Y, nodeType, whiteList, blackList, tol, maxStep, restart, seed, verbose)
}


