// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// edgeOnLoop
bool edgeOnLoop(int fromNode, int toNode, const Rcpp::List& parSet);
RcppExport SEXP _dagbagMv2_edgeOnLoop(SEXP fromNodeSEXP, SEXP toNodeSEXP, SEXP parSetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type fromNode(fromNodeSEXP);
    Rcpp::traits::input_parameter< int >::type toNode(toNodeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type parSet(parSetSEXP);
    rcpp_result_gen = Rcpp::wrap(edgeOnLoop(fromNode, toNode, parSet));
    return rcpp_result_gen;
END_RCPP
}
// hc1
Rcpp::List hc1(const Rcpp::NumericMatrix& Y, const Rcpp::CharacterVector& nodeType, const Rcpp::LogicalMatrix& whiteList, const Rcpp::LogicalMatrix& blackList, double tol, int maxStep, int seed, bool flip, bool verbose, bool debug, bool addDeleteOnly);
RcppExport SEXP _dagbagMv2_hc1(SEXP YSEXP, SEXP nodeTypeSEXP, SEXP whiteListSEXP, SEXP blackListSEXP, SEXP tolSEXP, SEXP maxStepSEXP, SEXP seedSEXP, SEXP flipSEXP, SEXP verboseSEXP, SEXP debugSEXP, SEXP addDeleteOnlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type nodeType(nodeTypeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalMatrix& >::type whiteList(whiteListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalMatrix& >::type blackList(blackListSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxStep(maxStepSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type flip(flipSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< bool >::type addDeleteOnly(addDeleteOnlySEXP);
    rcpp_result_gen = Rcpp::wrap(hc1(Y, nodeType, whiteList, blackList, tol, maxStep, seed, flip, verbose, debug, addDeleteOnly));
    return rcpp_result_gen;
END_RCPP
}
// hc_
Rcpp::List hc_(const Rcpp::NumericMatrix& Y, const Rcpp::CharacterVector& nodeType, const Rcpp::LogicalMatrix& whiteList, const Rcpp::LogicalMatrix& blackList, double tol, int maxStep, int restart, int seed, bool verbose, bool debug, bool addDeleteOnly);
RcppExport SEXP _dagbagMv2_hc_(SEXP YSEXP, SEXP nodeTypeSEXP, SEXP whiteListSEXP, SEXP blackListSEXP, SEXP tolSEXP, SEXP maxStepSEXP, SEXP restartSEXP, SEXP seedSEXP, SEXP verboseSEXP, SEXP debugSEXP, SEXP addDeleteOnlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type nodeType(nodeTypeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalMatrix& >::type whiteList(whiteListSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalMatrix& >::type blackList(blackListSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxStep(maxStepSEXP);
    Rcpp::traits::input_parameter< int >::type restart(restartSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< bool >::type addDeleteOnly(addDeleteOnlySEXP);
    rcpp_result_gen = Rcpp::wrap(hc_(Y, nodeType, whiteList, blackList, tol, maxStep, restart, seed, verbose, debug, addDeleteOnly));
    return rcpp_result_gen;
END_RCPP
}
// score_shd_freq_cpp
Rcpp::IntegerMatrix score_shd_freq_cpp(const Rcpp::NumericMatrix& freq, double alpha, double threshold, const Rcpp::LogicalMatrix& whitelist, const Rcpp::LogicalMatrix& blacklist, bool verbose);
RcppExport SEXP _dagbagMv2_score_shd_freq_cpp(SEXP freqSEXP, SEXP alphaSEXP, SEXP thresholdSEXP, SEXP whitelistSEXP, SEXP blacklistSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalMatrix& >::type whitelist(whitelistSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalMatrix& >::type blacklist(blacklistSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(score_shd_freq_cpp(freq, alpha, threshold, whitelist, blacklist, verbose));
    return rcpp_result_gen;
END_RCPP
}
// score_shd_cpp
Rcpp::IntegerMatrix score_shd_cpp(const Rcpp::NumericVector& bootAdj, double alpha, double threshold, const Rcpp::LogicalMatrix& whitelist, const Rcpp::LogicalMatrix& blacklist, bool verbose);
RcppExport SEXP _dagbagMv2_score_shd_cpp(SEXP bootAdjSEXP, SEXP alphaSEXP, SEXP thresholdSEXP, SEXP whitelistSEXP, SEXP blacklistSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type bootAdj(bootAdjSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalMatrix& >::type whitelist(whitelistSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalMatrix& >::type blacklist(blacklistSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(score_shd_cpp(bootAdj, alpha, threshold, whitelist, blacklist, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dagbagMv2_edgeOnLoop", (DL_FUNC) &_dagbagMv2_edgeOnLoop, 3},
    {"_dagbagMv2_hc1", (DL_FUNC) &_dagbagMv2_hc1, 11},
    {"_dagbagMv2_hc_", (DL_FUNC) &_dagbagMv2_hc_, 11},
    {"_dagbagMv2_score_shd_freq_cpp", (DL_FUNC) &_dagbagMv2_score_shd_freq_cpp, 6},
    {"_dagbagMv2_score_shd_cpp", (DL_FUNC) &_dagbagMv2_score_shd_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_dagbagMv2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
